export const displayNames: Record<string, string> = {
  manager: "Administrador",
  add: "Agregar",
  shop: "Tienda",
  user: "Usuario",
  categories: "Categorías",
  subcategories: "Subcategorías",
  products: "Productos",
  brands: "Marcas",
  sizes: "Talles",
  profile: "Perfil",
  prices: "Precios",
  sales: "Ventas",
  reports: "Reportes",
  support: "Soporte",
  createemployee: "Nuevo empleado",
  addProduct: "Agregar producto",
  addVariant: "Agregar variante",
  addcategory: "Agregar categoría",
  addsubcategory: "Agregar subcategoría",
  addbrand: "Agregar marca",
  addsize: "Agregar talle",
  addcolor: "Agregar color",
  pricesupload: "Cargar precios",
  shipping: "Envíos",
  editlists: "Editar listas",
  cashcount: "Arqueo de caja",
  cashregister: "Corte de caja",
  orders: "Órdenes",
  settingsmanager: "Configuraciones",
  settings: "Configuraciones",
  overview: "Vista General",
  cashier: "Caja",
  audits: "Arqueo de caja",
  cuts: "Corte de caja",
  reportsemployee: "Reporte de Ventas",
  companysubscription: "Subscripción de Compañías" ,
};
