const tempData = [
  {
    title: "Guardians of the Galaxy Vol. 2",
    year: 2017,
    director: "James Gunn",
    duration: "2h 16min",
    genre: ["Action", "Adventure", "Comedy"],
    rate: 7.6,
    poster: "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    year: 1977,
    director: "George Lucas",
    duration: "2h 1min",
    genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    rate: 8.6,
    poster: "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    director: "Peter Jackson",
    duration: "2h 58min",
    genre: ["Action", "Adventure", "Drama", "Fantasy"],
    rate: 8.9,
    poster: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
  },
  {
    title: "Dune",
    year: 2021,
    director: "Denis Villeneuve",
    duration: "2h 35min",
    genre: ["Sci-Fi", "Adventure", "Drama", "Epic Film"],
    rate: 8,
    poster: "https://m.media-amazon.com/images/I/61CRq2R6i4L._AC_SL1024_.jpg",
  },
  {
    title: "El Secreto De Sus Ojos",
    year: 2009,
    director: "Juan José Campanella",
    duration: "2h 9min",
    genre: ["Thriller", "Mystery", "Drama", "Romance"],
    rate: 8.2,
    poster: "https://m.media-amazon.com/images/I/51Ff+OgeJZL._AC_.jpg",
  },
  {
    title: "Predestination",
    year: 2014,
    director: "Michael Spierig & Peter Spierig",
    duration: "1h 37min",
    genre: ["Sci-Fi", "Thriller", "Mystery", "Action"],
    rate: 7.4,
    poster: "https://m.media-amazon.com/images/I/7159HQnWgTL._AC_SL1500_.jpg",
  },
  {
    title: "Esperando La Carroza",
    year: 1985,
    director: "Alejandro Doria",
    duration: "1h 34min",
    genre: ["Comedy"],
    rate: 8,
    poster: "https://m.media-amazon.com/images/I/61J1c5x9MVL._AC_.jpg",
  },
  {
    title: "Asesinato En El Senado De La Nación",
    year: 1984,
    director: "Juan José Jusid",
    duration: "1h 45min",
    genre: ["Drama", "Crime", "Politics", "Historical"],
    rate: 7,
    poster: "https://m.media-amazon.com/images/I/61TWZlbLvYL._AC_.jpg",
  },
  {
    title: "Nazareno Cruz Y El Lobo",
    year: 1975,
    director: "Leonardo Favio",
    duration: "1h 32min",
    genre: ["Drama", "Horror", "Fantasy"],
    rate: 6.9,
    poster: "https://www.benitomovieposter.com/catalog/images/movieposter/6231.jpg",
  },
];
